### ISSUE TITLE
SSG 化

### ISSUE THREAD

**Issue by lemonadern** [koyosai-4I-2022/koyosai-4I-home-page#41]
# Summary 
@Dz0526  Ranking 以外のページは静的なので、SSGしちゃうのはどうでしょうか :upside_down_face:

**Comment by Dz0526** [comment]
いいっすねー😎　@lemonadern 頼んだ！！

**Comment by lemonadern** [comment]
~~- [ ] System ページ を SSGにする~~

**Comment by lemonadern** [comment]
データフェッチングが必要かつ静的なデータはこのアプリにはなさそうなので、Next.jsのデフォルトに任せてClose
https://nextjs.org/docs/basic-features/pages#static-generation-without-data
