### ISSUE TITLE
useEffect を修正する

### ISSUE THREAD

**Issue by lemonadern** [koyosai-4I-2022/koyosai-4I-home-page#42]
# Summary
https://github.com/koyosai-4I-2022/koyosai-4I-home-page/blob/main/src/pages/about.tsx#L34toL36
全然動くから直さなくてもいいんだけど、↑の useEffect の実装直してもいい？ :upside_down_face: 
Linter の warn が出てると思う

@Dz0526

**Comment by Dz0526** [comment]
@lemonadern ありがとう！助かる
