### ISSUE TITLE
OGP画像を設定

### ISSUE THREAD

**Issue by Dz0526** [koyosai-4I-2022/koyosai-4I-home-page#52]
### 内容
- withmosaic.png とかを設定いいかな？

### OPGとは
- https://g.co/kgs/uBdcHR
- https://ogimage.tsmallfield.com/

**Comment by tnkryoga** [comment]
@Dz0526 
どんな感じか確認したくて、いろいろ調べた感じ一回mergeして　
https://koyosai-4i-home-page.versel.app
のほうにあげないと確認できない感じなんだけど...
なんかいいデバッグ方法知ってたりする？

**Comment by tnkryoga** [comment]
あとこれってtwitterとかで見る想定？Facebookとかも？

**Comment by tnkryoga** [comment]
@Dz0526

**Comment by Dz0526** [comment]
@tnkryoga 
localhost のやつをLINEでリンク共有したらどうなる？見れないようだったら今のブランチをpushしてくれない？

**Comment by tnkryoga** [comment]
LINE見えなかったから一回pushするね
